# Generated by Django 5.1.1 on 2025-05-14 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_receiver'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donor',
            name='address',
        ),
        migrations.RemoveField(
            model_name='donor',
            name='email',
        ),
        migrations.AddField(
            model_name='donor',
            name='aadhaar',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='donor',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='donor',
            name='hla_a',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='donor',
            name='hla_b',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='donor',
            name='hla_dr',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='donor',
            name='hospital',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='donor',
            name='place',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='donor',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
