# Generated by Django 5.1.1 on 2025-05-14 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_donor_address_remove_donor_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='receiver',
            name='aadhaar',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='receiver',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='receiver',
            name='hla_a',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='receiver',
            name='hla_b',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='receiver',
            name='hla_dr',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
