# Generated by Django 5.1.1 on 2025-05-14 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_receiver_aadhaar_receiver_gender_receiver_hla_a_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='receiver',
            name='hospital',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='receiver',
            name='place',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
