# Generated by Django 5.1.1 on 2025-05-16 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_receiver_hospital_receiver_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='receiver',
            name='matched_donor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.donor'),
        ),
    ]
