# Generated by Django 5.1.6 on 2025-05-19 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_hospitalprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='receiver',
            name='match_score',
            field=models.FloatField(default=0.0),
        ),
    ]
